apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
data:
  database-name: cGV0Y2xpbmlj
  database-password: cGV0Y2xpbmlj
  database-root-password: cGV0Y2xpbmlj
  database-user: cGV0Y2xpbmlj
