apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: counter-database
    app.kubernetes.io/part-of: counter
  name: counter-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi