apiVersion: v1
kind: Secret
metadata:
  name: counter-database
  labels:
    app: counter-database
    app.kubernetes.io/part-of: counter
type: Opaque
data:
  DB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # root
  database-name: ZGF0YWJhc2UtbmFtZQ==
  database-password: ZGF0YWJhc2UtcGFzc3dvcmQ=
  database-user: ZGF0YWJhc2UtdXNlcg==
  BACKEND_URL: aHR0cHM6Ly9jb3VudGVyLWJhY2tlbmQtemxpYy1ncGVydm9yZmkxLmFwcHMuZXhvc2NhbGUtY2gtZ3ZhLTItMC5hcHB1aW8uY2xvdWQ= ## https://counter-backend-zlic-gpervorfi1.apps.exoscale-ch-gva-2-0.appuio.cloud/
  DB_HOST: Y291bnRlci1kYXRhYmFzZQ== # counter-database
  DB_PORT: MzMwNg== # 3306
  BACKEND_PASSPHRASE: c2VjcmV0 # secret
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20= # admin@example.com
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4= # admin