apiVersion: v1
kind: Secret
metadata:
  name: counter-database
type: Opaque
data:
  database-name: ZGF0YWJhc2UtbmFtZQ==
  database-password: ZGF0YWJhc2UtcGFzc3dvcmQ=
  database-user: ZGF0YWJhc2UtdXNlcg==
